services:
  accountlextaticoapi:
    image: ${DOCKER_REGISTRY-}accountlextaticoapi
    container_name: account_lextatico_api
    build:
      context: .
      dockerfile: src/Account.Lextatico.Api/Dockerfile-debug
    ports:
      - 9002:9002
      - 9003:9003
    networks:
      - Lextatico
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOCAL_DEVELOPMENT=True
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
